# Setup
title:               Eunbin-Ha
tagline:             '은빈의 개발 및 학습 기록'
description:         '저의 사적인 공간입니다. 감상은 자유입니다.'
url:                 https://ekna0187.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Eunbin-Ha
  url:               https://github.com/ekna0187
  email:             ekna0187@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
